### ISSUE TITLE
fix: SQLite DB locked and crashes.

### ISSUE THREAD

**Issue by pekasen** [Leibniz-HBI/ponyexpress#97]
```pytb
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1144, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 702, in do_commit
    dbapi_connection.commit()
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/spiderexpress", line 8, in <module>
    sys.exit(cli())
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/spiderexpress/cli.py", line 53, in start
    ctx.obj.start(config)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/transitions/core.py", line 406, in trigger
    return self.machine._process(func)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/transitions/core.py", line 1251, in _process
    self._transition_queue[0]()
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/transitions/core.py", line 420, in _trigger
    self._process(event_data)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/transitions/core.py", line 443, in _process
    if trans.execute(event_data):
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/transitions/core.py", line 278, in execute
    self._change_state(event_data)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/transitions/core.py", line 289, in _change_state
    dest.enter(event_data)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/transitions/core.py", line 130, in enter
    event_data.machine.callbacks(self.on_enter, event_data)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/transitions/core.py", line 1174, in callbacks
    self.callback(func, event_data)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/transitions/core.py", line 1195, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/spiderexpress/spider.py", line 439, in gather_node_data
    self._dispatch_connector_for_node_(task, task.connector)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/spiderexpress/spider.py", line 573, in _dispatch_connector_for_node_
    insert_layer_dense_edge(
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/spiderexpress/model.py", line 126, in insert_layer_dense_edge
    session.commit()
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1320, in commit
    trans.commit()
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2631, in commit
    self._do_commit()
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2736, in _do_commit
    self._connection_commit_impl()
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2707, in _connection_commit_impl
    self.connection._commit_impl()
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1146, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1144, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 702, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
```

**Comment by pekasen** [comment]
```pytb
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT application_state.id AS application_state_id, application_state.version AS application_state_version, application_state.iteration AS application_state_iteration
FROM application_state
WHERE application_state.id = ?]
[parameters: ('1',)]
```

**Comment by pekasen** [comment]
```pytb

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1144, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 702, in do_commit
    dbapi_connection.commit()
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/spiderexpress", line 8, in <module>
    sys.exit(cli())
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/spiderexpress/cli.py", line 53, in start
    ctx.obj.start(config)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/transitions/core.py", line 406, in trigger
    return self.machine._process(func)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/transitions/core.py", line 1251, in _process
    self._transition_queue[0]()
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/transitions/core.py", line 420, in _trigger
    self._process(event_data)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/transitions/core.py", line 443, in _process
    if trans.execute(event_data):
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/transitions/core.py", line 278, in execute
    self._change_state(event_data)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/transitions/core.py", line 289, in _change_state
    dest.enter(event_data)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/transitions/core.py", line 130, in enter
    event_data.machine.callbacks(self.on_enter, event_data)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/transitions/core.py", line 1174, in callbacks
    self.callback(func, event_data)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/transitions/core.py", line 1195, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/spiderexpress/spider.py", line 439, in gather_node_data
    self._dispatch_connector_for_node_(task, task.connector)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/spiderexpress/spider.py", line 573, in _dispatch_connector_for_node_
    insert_layer_dense_edge(
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/spiderexpress/model.py", line 126, in insert_layer_dense_edge
    session.commit()
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1320, in commit
    trans.commit()
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2631, in commit
    self._do_commit()
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2736, in _do_commit
    self._connection_commit_impl()
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2707, in _connection_commit_impl
    self.connection._commit_impl()
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1146, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1144, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/home/ubuntu/.local/share/uv/tools/spiderexpress/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 702, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```
